name = "LinkageDisequilibrium"
uuid = "3681d880-91a7-4775-81c1-fa9def966640"
authors = "Sunoru <s@sunoru.com"
repo = "https://github.com/sunoru/LinkageDisequilibrium.jl.git"
version = "0.1.0"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
